import { useState } from "react";
import { useNavigation } from "@react-navigation/native";
import type { NativeStackNavigationProp } from "@react-navigation/native-stack";
import * as FileSystem from "expo-file-system/legacy";
import * as Sharing from "expo-sharing";
import { Alert, StyleSheet, Text, View } from "react-native";
import { clearToken, readToken, reportUrl } from "../api/client";
import { useAuth } from "../auth/AuthContext";
import { Button, Heading, Notice, Page, SectionLabel } from "../components/ui";
import type { RootStackParamList } from "../navigation/types";
import { colors } from "../theme";

type RootNavigation = NativeStackNavigationProp<RootStackParamList>;

export function ReportsScreen() {
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [fileUri, setFileUri] = useState("");
  const [filename, setFilename] = useState("");

  async function generateReport() {
    setBusy(true);
    setError("");
    try {
      const token = await readToken();
      const date = new Date().toISOString().slice(0, 10);
      const fallbackName = `exploration-log-${date}.pdf`;
      const localUri = `${FileSystem.documentDirectory}${fallbackName}`;
      const result = await FileSystem.downloadAsync(reportUrl(), localUri, {
        headers: token ? { Authorization: `Bearer ${token}` } : {},
      });
      if (result.status < 200 || result.status >= 300) {
        throw new Error(result.status === 401 ? "Your session expired. Sign in again to download the report." : `Report download failed (${result.status}).`);
      }
      const disposition = result.headers?.["content-disposition"] ?? "";
      const match = disposition.match(/filename="?([^";]+)"?/i);
      const actualName = match?.[1] ?? fallbackName;
      setFileUri(result.uri);
      setFilename(actualName);
    } catch (reason) {
      setError(reason instanceof Error ? reason.message : "Could not download your report.");
    } finally {
      setBusy(false);
    }
  }

  async function shareReport() {
    if (!fileUri) return;
    try {
      if (!(await Sharing.isAvailableAsync())) {
        setError("Sharing is not available on this device.");
        return;
      }
      await Sharing.shareAsync(fileUri, { mimeType: "application/pdf", dialogTitle: "Share exploration log", UTI: "com.adobe.pdf" });
    } catch (reason) {
      setError(reason instanceof Error ? reason.message : "Could not open the system share sheet.");
    }
  }

  return (
    <Page>
      <Heading title="Reports" subtitle="Generate a fresh PDF from your live site records." />
      <View style={styles.card}>
        <SectionLabel>EXPLORATION LOG</SectionLabel>
        <Text style={styles.copy}>Your site submissions, statuses, locations and review notes, generated by the existing reports service.</Text>
        {error ? <Notice>{error}</Notice> : null}
        {filename ? <Notice tone="success">Downloaded {filename}</Notice> : null}
        <Button label={busy ? "Generating report…" : "Generate PDF"} icon="↓" onPress={() => void generateReport()} disabled={busy} />
        {fileUri ? <Button label="Open or share PDF" icon="↗" variant="secondary" onPress={() => void shareReport()} /> : null}
      </View>
    </Page>
  );
}

export function SettingsScreen() {
  const { user, signOut } = useAuth();
  const navigation = useNavigation<RootNavigation>();
  const [busy, setBusy] = useState(false);

  function confirmLogout() {
    Alert.alert("Sign out?", "Your secure session will be cleared from this device.", [
      { text: "Cancel", style: "cancel" },
      { text: "Sign out", style: "destructive", onPress: () => { void logout(); } },
    ]);
  }

  async function logout() {
    setBusy(true);
    await clearToken();
    await signOut();
    setBusy(false);
  }

  return (
    <Page>
      <Button label="←  Field tools" variant="quiet" onPress={() => navigation.goBack()} />
      <Heading title="Settings" subtitle="Your signed-in department profile." />
      <View style={styles.profile}>
        <View style={styles.avatar}><Text style={styles.initials}>{`${user?.firstName?.[0] ?? "F"}${user?.lastName?.[0] ?? "O"}`.toUpperCase()}</Text></View>
        <View style={styles.profileCopy}><Text style={styles.name}>{user ? `${user.firstName} ${user.lastName}` : "Field Officer"}</Text><Text style={styles.email}>{user?.email}</Text><View style={styles.role}><Text style={styles.roleText}>{user?.role?.name ?? "FIELD_OFFICER"}</Text></View></View>
      </View>
      <View style={styles.card}><SectionLabel>ACCOUNT</SectionLabel><ProfileRow label="First name" value={user?.firstName ?? "—"} /><ProfileRow label="Last name" value={user?.lastName ?? "—"} /><ProfileRow label="Email" value={user?.email ?? "—"} /><ProfileRow label="Role" value={user?.role?.name ?? "FIELD_OFFICER"} /></View>
      <Button label={busy ? "Signing out…" : "Sign out"} variant="danger" icon="↪" onPress={confirmLogout} disabled={busy} />
    </Page>
  );
}

function ProfileRow({ label, value }: { label: string; value: string }) {
  return <View style={styles.profileRow}><Text style={styles.profileLabel}>{label}</Text><Text style={styles.profileValue}>{value}</Text></View>;
}

const styles = StyleSheet.create({
  card: { padding: 16, gap: 14, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderRadius: 5 },
  copy: { color: colors.muted, fontSize: 13, lineHeight: 20 },
  profile: { paddingVertical: 18, borderBottomWidth: 1, borderTopWidth: 1, borderColor: colors.line, flexDirection: "row", alignItems: "center", gap: 13 },
  avatar: { width: 56, height: 56, borderRadius: 28, alignItems: "center", justifyContent: "center", backgroundColor: colors.forest },
  initials: { color: "#FFFFFF", fontSize: 18, fontWeight: "700" },
  profileCopy: { flex: 1, gap: 4 },
  name: { color: colors.ink, fontSize: 17, fontWeight: "700" },
  email: { color: colors.muted, fontSize: 12 },
  role: { alignSelf: "flex-start", marginTop: 3, backgroundColor: colors.forestLight, paddingHorizontal: 7, paddingVertical: 4 },
  roleText: { color: colors.forest, fontSize: 9, fontWeight: "800", letterSpacing: 0.7 },
  profileRow: { flexDirection: "row", justifyContent: "space-between", gap: 15 },
  profileLabel: { color: colors.muted, fontSize: 12 },
  profileValue: { flex: 1, textAlign: "right", color: colors.ink, fontSize: 12, fontWeight: "600" },
});